@hostname = http://localhost
@port = 8080
@host = {{hostname}}:{{port}}




POST {{host}}/Passwords/reset
Content-Type: application/json

{
    "Email" : "a1c68b75@bvmtk.com"
}

###

POST {{host}}/Passwords/resetValidate
Content-Type: application/json

{
    "Email" : "a1c68b75@bvmtk.com",
    "Password" : "newpassword",
    "Token" : "qweryasdf"
}