// vscode extension: humao.rest-client
// just click "send request" above each URL

// in the case of JWTs, login with a user and copy paste response JWT
// JWTs are valid for an hour (subject to change) so you don't need to constantly login

@hostname = http://localhost
@port = 5000
@host = {{hostname}}:{{port}}




POST {{host}}/Users/register
Content-Type: application/json

{
    "Email" : "salt5@gmail.com",
    "Password" : "salt5",
    "FirstName" : "first",
    "LastName" : "last",
    "Admin": false
}

###
// (this is associated with a valid account)
POST {{host}}/Users/login
Content-Type: application/json

{
    "Email": "salt5@gmail.com",
    "Password": "salt5"
}

###
POST {{host}}/Users/
Content-Type: application/json

{
    "JWT": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6InNhbHQ1QGdtYWlsLmNvbSIsIkFkbWluIjpmYWxzZSwiaWF0IjoxNjE4MTkzMTk4LCJleHAiOjE2MTgxOTY3OTh9.L7WeIilitHl96aCauxJ_YcRxqthL-MdGynHEPlujYpM"
}

###

POST {{host}}/JWT/verify
Content-Type: application/json

{
    "JWT": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6InNhbHQ1QGdtYWlsLmNvbSIsIkFkbWluIjpmYWxzZSwiaWF0IjoxNjE3NDEyMTgyLCJleHAiOjE2MTc0MTU3ODJ9.39ny2Nb85A3xc1ZJSRdsZoXWa7N1S9b-8mfiRf6uge4"
}

###

POST {{host}}/JWT/refresh
Content-Type: application/json

{
    "JWT": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6InNhbHQ1QGdtYWlsLmNvbSIsIkFkbWluIjpmYWxzZSwiaWF0IjoxNjE3NDEyMTgyLCJleHAiOjE2MTc0MTU3ODJ9.39ny2Nb85A3xc1ZJSRdsZoXWa7N1S9b-8mfiRf6uge4"
}
