// vscode extension: humao.rest-client
// just click "send request" above each URL

// in the case of JWTs, login with a user and copy paste response JWT
// JWTs are valid for an hour (subject to change) so you don't need to constantly login

@hostname = http://localhost
@port = 8080
@host = {{hostname}}:{{port}}



# Register
POST {{host}}/Users/register
Content-Type: application/json

{
    "Email" : "6b2e2ade@bvmtk.com",
    "Password" : "123",
    "FirstName" : "first",
    "LastName" : "last"
}

###

POST {{host}}/Users/verify/
Content-Type: application/json

{
    "uniqueString" : "831065728"
}

### This is where we paste the verification code when logging in 1st time
// (this is associated with a valid account)
POST {{host}}/Users/login
Content-Type: application/json

{
    "Email": "thechanman.potato@gmail.com",
    "Password": "123",
    "Verification": ""
}

###
POST {{host}}/Users/
Content-Type: application/json

{
    "JWT": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6InNhbHQzQGdtYWlsLmNvbSIsImlhdCI6MTYxODk4MTM4MiwiZXhwIjoxNjE4OTg0OTgyfQ.b3nXJt6BauUetC-6ewXVCAo76DUvXuP2Ym5OoayYJjI"
}

###

POST {{host}}/Users/edit
Content-Type: application/json

{
    "Password": "salt2",
    "FirstName": "FirstName",
    "LastName": "LastName",
    "JWT": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6InNhbHQyQGdtYWlsLmNvbSIsImlhdCI6MTYxODg4NDIzMiwiZXhwIjoxNjE4ODg3ODMyfQ.wTTUuiwlaoLaD5KK7ipt1Vchv428PE3H8fbMuveYDr8"
}

###

POST {{host}}/Users/delete
Content-Type: application/json

{
    "JWT": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6ImExYzY4Yjc1QGJ2bXRrLmNvbSIsIkFkbWluIjpmYWxzZSwiaWF0IjoxNjE4OTY0MTA5LCJleHAiOjE2MTg5Njc3MDl9.749ymgFoxxrRqV7b3y__I71rES-OSlivYKb5C7FeG9I"
}

###

POST {{host}}/Users/devDelete
Content-Type: application/json

{
    "Email" : "ttt@ttt.com"
}

### Punch in email and give it a password to reset

POST {{host}}/Users/devPassword
Content-Type: application/json

{
    "Email" : "andrew13560@gmail.com",
    "Password": "123"
}